import AgrawalCore

/-!
Reproducible `#print axioms` surface for the headline declarations.

The expected output contains only Lean/Mathlib's standard logical axioms:
`propext`, `Classical.choice`, and `Quot.sound` (with
`Classical.choice` absent where it is not needed). No project-defined axiom is
introduced.
-/

#print axioms AgrawalCore.moment_covariance
#print axioms AgrawalCore.pow_succ_eq_one_of_moment_ne_zero
#print axioms AgrawalCore.golden_moment_factorization
#print axioms AgrawalCore.zmod_golden_moment_index
#print axioms AgrawalCore.quintic_index_indexedMomentUnit_eq_moment
#print axioms AgrawalCore.indexedMomentUnit_two_eq_quadraticMomentUnit
#print axioms AgrawalCore.cyclotomic_quadratic_moment_eq_three_golden_index
#print axioms AgrawalCore.quintic_covariance_of_local_row
#print axioms AgrawalCore.localS5_unit_rows
#print axioms AgrawalCore.localS5_golden_moment_obstruction
#print axioms AgrawalCore.localS5_golden_order_constraint
#print axioms AgrawalCore.localS5_canonical_golden_moment_obstruction
#print axioms AgrawalCore.localS5_canonical_golden_order_constraint
#print axioms AgrawalCore.localS5_canonical_quintic_locks_of_ne_one
#print axioms AgrawalCore.agrawal_fermat_shadow
#print axioms AgrawalCore.agrawal_two_adic_jaw
#print axioms AgrawalCore.orderOf_norm_power
#print axioms AgrawalCore.orderOf_norm_decomposition
#print axioms AgrawalCore.orderOf_norm_kernel
#print axioms AgrawalCore.defectProduct_threshold
#print axioms AgrawalCore.odd_defectProduct_threshold
#print axioms AgrawalCore.odd_defectProduct_normal_iff
#print axioms AgrawalCore.defectMultiplier_iff
#print axioms AgrawalCore.defectMultiplier_le_div_iff
#print axioms AgrawalCore.pureCandidate_below_sq_iff
#print axioms AgrawalCore.twistedCandidate_positive_iff
#print axioms AgrawalCore.lenstra_proposition_card
#print axioms AgrawalCore.partition_forced
#print axioms AgrawalCore.hasOrderFourTransport_iff_goldenH_support
#print axioms AgrawalCore.no_squarefree_counterexample_of_no_witnesses
#print axioms AgrawalCore.primitiveSupport_iff_fourCoefficientGcd
#print axioms AgrawalCore.one_order_dvd_eight_of_single_odd_prime
#print axioms AgrawalCore.gamma_pow_formula
#print axioms AgrawalCore.noncanonicalP_prime
#print axioms AgrawalCore.noncanonical_inert
#print axioms AgrawalCore.noncanonical_five_order_certificate
#print axioms AgrawalCore.noncanonical_five_order
#print axioms AgrawalCore.split_pair_zero_iff_four_coefficient_gcd
#print axioms AgrawalCore.eval₂_cyclotomic_gamma_coeffs
#print axioms AgrawalCore.primitiveFourVanish_iff_dvd_D
#print axioms AgrawalCore.canonicalSignature_unique
#print axioms AgrawalCore.primitiveFourVanish_exact_order_profile
#print axioms AgrawalCore.dvd_primitiveFourCoefficientD_exact_order_profile
#print axioms AgrawalCore.dvd_D_exact_scalar_profile
#print axioms AgrawalCore.neg_gamma_isSquare_iff_mod_five_one
#print axioms AgrawalCore.dvd_D_residual_multiplier_even_iff_mod_five_one
#print axioms AgrawalCore.dvd_D_residual_multiplier_even_iff_five_dvd
#print axioms AgrawalCore.dvd_D_ten_dvd_residual_multiplier_iff_mod_five_one
#print axioms AgrawalCore.golden_root_mod_five_split
#print axioms AgrawalCore.dvd_D_residual_multiplier_branch_dichotomy
#print axioms AgrawalCore.dvd_D_residual_multiplier_mod_ten_table
#print axioms AgrawalCore.dvd_D_class_specific_lower_bounds
#print axioms AgrawalCore.shifted_generator_isPower_iff
#print axioms AgrawalCore.neg_isPower_iff_residual_multiplier_dvd
#print axioms AgrawalCore.dvd_D_neg_gamma_isPower_iff_dvd
#print axioms AgrawalCore.dvd_D_neg_gamma_isPower_iff_lcm_five_dvd
#print axioms AgrawalCore.dvd_D_neg_gamma_isFourthPower_iff_twenty_dvd
#print axioms AgrawalCore.dvd_D_order_product_residual_factorization
#print axioms AgrawalCore.dvd_D_ten_mul_order_product_dvd_card_sub_one
#print axioms AgrawalCore.no_split_single_odd_support
#print axioms AgrawalCore.threeFactor_finalRow_size_exclusion
#print axioms AgrawalCore.localRow_order_le_max
#print axioms AgrawalCore.normalDefect_forces_sq_lt_complement
#print axioms AgrawalCore.pureRow_dvd_product_sub_one
#print axioms AgrawalCore.twistedRow_dvd_sq_sub_product
#print axioms AgrawalCore.twistedRow_product_le_sq_sub_order
#print axioms AgrawalCore.pureRow_order_le_product_sub_one
#print axioms AgrawalCore.twistedRow_order_le_absGap
#print axioms AgrawalCore.mitm_secondProduct_unique
#print axioms AgrawalCore.finalSmallRow_transport
#print axioms AgrawalCore.smallRows_triangle
#print axioms AgrawalCore.localRow_oddShadow
#print axioms AgrawalCore.coprime_right_of_dvd_mul_sub_one
#print axioms AgrawalCore.sharedOddSupport_dvd_gap
#print axioms AgrawalCore.pureSmallRow_transport
#print axioms AgrawalCore.twistedSmallRow_transport
#print axioms AgrawalCore.pureSmallRow_lift_iff
#print axioms AgrawalCore.twistedSmallRow_lift_iff
#print axioms AgrawalCore.boundedLift_exclusion
